import one from "/public/images/gridSix.png";
import two from "/public/images/gridSeven.png";
import three from "/public/images/gridEight.png";
import four from "/public/images/gridThree.png";
import five from "/public/images/guy.png";
import six from "/public/images/image-five.png";
import seven from "/public/images/image-four.png";
import eight from "/public/images/image-one.png";
import nine from "/public/images/image-six.png";
import ten from "/public/images/image-three.png";
import eleven from "/public/images/image-two.png";
import twelve from "/public/images/gridNine.png";
import thirteen from "/public/images/image-seven.png";
import fourteen from "/public/images/image-eight.png";
import fifteen from "/public/images/image-nine.png";
import sixteen from "/public/images/image-ten.png";
import seventeen from "/public/images/image-eleven.png";

export const images = [
  {
    id: 0,
    url: one,
    brand: "Forever 21",
    newPrice: "Rs. 700",
    oldPrice: "Rs. 1000",
    discount: "30%",
    product: "Knit Tops",
    category: "Women",
  },
  {
    id: 1,
    url: two,
    brand: "Here&Now",
    newPrice: "Rs. 400",
    oldPrice: "Rs. 800",
    discount: "50%",
    product: "Tees",
    category: "Women",
  },
  {
    id: 2,
    url: three,
    brand: "Tokyo Talkies",
    newPrice: "Rs. 700",
    oldPrice: "Rs. 1000",
    discount: "30%",
    product: "Two Piece",
    category: "Women",
  },
  {
    id: 3,
    url: four,
    brand: "Levis",
    newPrice: "Rs. 1200",
    oldPrice: "Rs. 1500",
    discount: "20%",
    product: "Cargo Jacket",
    category: "Women",
  },
  {
    id: 4,
    url: five,
    brand: "Forever 21",
    newPrice: "Rs. 1250",
    oldPrice: "Rs. 1400",
    discount: "11%",
    product: "Mens Biker Jacket",
    category: "Men",
  },
  {
    id: 5,
    url: six,
    brand: "Here&Now",
    newPrice: "Rs. 370",
    oldPrice: "Rs. 640",
    discount: "42%",
    product: "Sweaters",
    category: "Women",
  },
  {
    id: 6,
    url: seven,
    brand: "Tokyo Talkies",
    newPrice: "Rs. 1800",
    oldPrice: "Rs. 3600",
    discount: "50%",
    product: "Womens Ball Gown",
    category: "Women",
  },
  {
    id: 7,
    url: eight,
    brand: "Roadster",
    newPrice: "Rs. 1200",
    oldPrice: "Rs. 1500",
    discount: "20%",
    product: "Womens Denim Jacket",
    category: "Women",
  },
  {
    id: 8,
    url: nine,
    brand: "Tokyo Talkies",
    newPrice: "Rs. 700",
    oldPrice: "Rs. 2100",
    discount: "66%",
    product: "International Wears",
    category: "Women",
  },
  {
    id: 9,
    url: ten,
    brand: "Levis",
    newPrice: "Rs. 700",
    oldPrice: "Rs. 1000",
    discount: "30%",
    product: "Shirts",
    category: "Women",
  },
  {
    id: 10,
    url: eleven,
    brand: "Forever 21",
    newPrice: "Rs. 1100",
    oldPrice: "Rs. 1300",
    discount: "15%",
    product: "Mens Biker Jacket",
    category: "Men",
  },
  {
    id: 11,
    url: twelve,
    brand: "Levis",
    newPrice: "Rs. 800",
    oldPrice: "Rs. 1000",
    discount: "20%",
    product: "Mens Shirts",
    category: "Men",
  },
  {
    id: 12,
    url: thirteen,
    brand: "Roadster",
    newPrice: "Rs. 1850",
    oldPrice: "Rs. 2100",
    discount: "12%",
    product: "Womens Coat",
    category: "Women",
  },
  {
    id: 13,
    url: fourteen,
    brand: "Here&Now",
    newPrice: "Rs. 460",
    oldPrice: "Rs. 530",
    discount: "13%",
    product: "Womens Blazer",
    category: "Women",
  },
  {
    id: 14,
    url: fifteen,
    brand: "Forever 21",
    newPrice: "Rs. 890",
    oldPrice: "Rs. 1300",
    discount: "31%",
    product: "Womens Classy Blouse",
    category: "Women",
  },
  {
    id: 15,
    url: sixteen,
    brand: "Levis",
    newPrice: "Rs. 610",
    oldPrice: "Rs. 650",
    discount: "6%",
    product: "Plain Dress",
    category: "Women",
  },
  {
    id: 16,
    url: seventeen,
    brand: "Roadster",
    newPrice: "Rs. 350",
    oldPrice: "Rs. 500",
    discount: "30%",
    product: "Mens Plain Tees",
    category: "Men",
  },
];
