language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $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
  local_dir: out
  edge: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
